### ISSUE TITLE
Unable to prepare setup for platform odense_reno.sensor: Platform not found (Exception importing custom_components.odense_reno.sensor)

### ISSUE THREAD

**Issue by MegZamani** [fars-fede-fire/odense_reno#1]
![image](https://github.com/fars-fede-fire/odense_reno/assets/6299989/3c090466-22c1-4893-804c-0515e790f8c2)

Hi,

I do use "odense_reno" 0.1.1 and i do get this error now,
It have worked well for a long time, can it be the new HA update maybe?
![image](https://github.com/fars-fede-fire/odense_reno/assets/6299989/f00b6d2d-6c87-4f61-abe4-826bacd2f307)

Home Assistant Core
Unable to prepare setup for platform odense_reno.sensor: Platform not found (Exception importing custom_components.odense_reno.sensor).
May 18, 2023 at 19:47:48 – (ERROR) setup.py
Unexpected exception importing platform custom_components.odense_reno.sensor
May 18, 2023 at 19:47:48 – (ERROR) Odense Renovation (custom integration)

System i do use:
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

BR
/Meg

**Comment by fars-fede-fire** [comment]
Thank you for noticing.
It seems that some additional parameters that where default earlier have to be set now.
I have made a new version (0.1.1.1) that works in my environment with Home Assistant version 2023.5.
Please let me know if you still get some errors

**Comment by MegZamani** [comment]
![IMG_3215](https://github.com/fars-fede-fire/odense_reno/assets/6299989/10fdaf14-6ed3-42f8-9048-bf2b77b2dd8a)

Perfect. I have just downloaded your new version 0.1.1.1 and it works perfectly again!

thanks for the update and the good work!

/Meg
